name: Self-Hosted Runner Test on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: selfhostlinux # runos self-hosted and label selfhostlinux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "Self-hosted runner is working!"
