name: Self-Hosted Runner Test on Ubuntu bypasssudo

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  install-and-manage-apache:
    runs-on: selfhostlinux
    steps:
      - name: Grant sudo permission without a password
        run: |
          sudo echo "$USER ALL=(ALL) NOPASSWD: /usr/bin/apt-get update, /usr/bin/apt-get install" | sudo tee /etc/sudoers.d/$USER
      - name: Install Apache
        id: install_apache
        run: |
           # sudo -S apt-get update && sudo apt-get install -y apache2
           # Method 1 test ok
           # echo 'Techlabvn@123' | sudo -S apt-get update && sudo -S apt-get install -y apache2
            # Method 2 using variable ok
            #export SUDO_PASSWORD='Techlabvn@123'
            #echo $SUDO_PASSWORD | sudo -S apt-get update && sudo -S apt-get install -y apache2
            sudo apt-get update && sudo apt-get install -y apache2
        shell: bash
    
