name: Self-Hosted Runner Test on Windows

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [onprem-selfhost] #self-hosted
    steps:
      - name: Run a command
        run: echo "Self-hosted runner is working!"
