name: Self-Hosted Runner Test on Ubuntu bypasssudo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-and-manage-apache:
    runs-on: selfhostlinux
    steps:
      - name: Install Apache
        id: install_apache
        shell: bash
        run: |
           # Method 1 test ok
           # echo 'Techlabvn@123' | sudo -S apt-get update && sudo -S apt-get install -y apache2
           # Method 2 using variable ok
           export SUDO_USER="${{ secrets.LINUXDEPLOY_USER }}"
           export SUDO_PASSWORD="${{ secrets.LINUXDEPLOY_PASSWORD }}"
         
           echo $SUDO_PASSWORD | su - $SUDO_USER
           echo $SUDO_PASSWORD | sudo apt-get update 
           echo $SUDO_PASSWORD | sudo apt-get install -y apache2

      - name: Stop Apache
        shell: bash
        run: sudo systemctl stop apache2

      - name: Start Apache
        shell: bash
        run: sudo systemctl start apache2
