name: Self-Hosted Runner Test on Ubuntu bypasssudo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-and-manage-apache:
    runs-on: selfhostlinux
    steps:
      - name: Install Apache
        id: install_apache
        run: |
           # Method 1 test ok
           # echo 'Techlabvn@123' | sudo -S apt-get update && sudo -S apt-get install -y apache2
            # Method 2 using variable ok
            export SUDO_PASSWORD="${{ secrets.LINUXDEPLOY_PASSWORD }}"
             echo $SUDO_PASSWORD | sudo -S apt-get update && sudo -S apt-get install -y apache2
             
      - name: Stop Apache
          run:sudo systemctl stop apache2
      - name: Start Apache
          run:sudo systemctl start apache2
        shell: bash
