name: Self-Hosted Runner Test on Windows

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [onprem-selfhost] #self-hosted
    steps:
      - name: Run a command # task 1
        run: echo "Self-hosted runner is working!"
      - name: Checkout code  # task 2 checkout code of your repository
        uses: actions/checkout@v2
      - name: Create Folder # create a folder C:\Temp
        run: mkdir C:\Temp\techlabvn_folder
  Stop_and_start_service_windows_update:
    runs-on: [onprem-selfhost] #self-hosted
    steps:
      - name: Stop Service
        run: net stop wuauserv
      - name: Start Service
        run: net start wuauserv
